name: NMLMobs
version: '1.0'
main: io.github.NoOne.nMLMobs.NMLMobs
api-version: '1.21'
depend:
  - DamagePlugin
loadbefore:
  - DamagePlugin
commands:
  nmlSummon:
    description: Spawns a custom NML mob
    usage: /<command> <name>
  nmlKill:
    description: Removes all NML mobs in a range
    usage: /<command> <range>